### ISSUE TITLE
GitHub за студенти 

### ISSUE THREAD

**Issue by karinakozarova** [fmi/ruby-course-projects#1]
Според https://education.github.com/pack GitHub за студенти е безплатен за **неограничен** брой private репозиторита. Може би трябва да се ъпдейтне в course_projects.md :smile:

**Comment by mitio** [comment]
@karinakozarova благодаря за уточнението :) Това може да е добър повод да пробваш да го редактираш и да отвориш нов pull request с предложение за промяна :)

Иначе, курсът в момента не е активен и тази неточност е незначителна дреболия, която, вярвам, ще бъде отстранена, ако някой ден има ново издание и се ползва същата схема за предаване на проекти, каквато е описана в ръководството.

**Comment by mitio** [comment]
Оправено от @karinakozarova.
